### ISSUE TITLE
(node:27808) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead (Use node --trace-deprecation ... to show where the warning was created) C:\Users\yousu\OneDrive\Desktop\NFT's\tweartgenerator\ArtGeneratorUpdated-main\src\main.js:46 var dna = Number(_str.split(":").shift()); ^  TypeError: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by deltaforce99** [TomorrowWontExist/ArtGeneratorUpdated#1]
Hey I have this issue, not sure if others are experiencing the same

(node:27808) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
C:\Users\yousu\OneDrive\Desktop\NFT's\tweartgenerator\ArtGeneratorUpdated-main\src\main.js:46
  var dna = Number(_str.split(":").shift());
                        ^

TypeError: Cannot read properties of undefined (reading 'split')

![image](https://user-images.githubusercontent.com/95902017/145667849-bc1895aa-c15e-4db1-8174-279214f08298.png)

![image](https://user-images.githubusercontent.com/95902017/145667863-66e1dba5-7e25-488d-ab6c-8194051d1a52.png)

**Comment by deltaforce99** [comment]
Update
After 2 days I've found the solution
You must put the package json atleast into the SRC folder
It was saying it couldn't find it but now it works!!!!.......
Checking with my collection in the morning when I swap out the folders in the "Layers" folder

![image](https://user-images.githubusercontent.com/95902017/145668201-8af18a3d-cc92-43ba-a0d8-4d8869cad547.png)

**Comment by deltaforce99** [comment]
![image](https://user-images.githubusercontent.com/95902017/145668219-9aa92c4b-b253-4170-882e-2019d63cf681.png)

**Comment by deltaforce99** [comment]
PS C:\Users\yousu\OneDrive\Desktop\NFT's\tweartgenerator\ArtGeneratorUpdated-main> npm install // I prefer NPM over Yarn
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\yousu\AppData\Local\npm-cache\_logs\2021-12-11T07_17_28_219Z-debug.log     
PS C:\Users\yousu\OneDrive\Desktop\NFT's\tweartgenerator\ArtGeneratorUpdated-main> git clone https://github.com/TomorrowWontExist/ArtGeneratorUpdated.git
fatal: destination path 'ArtGeneratorUpdated' already exists and is not an empty directory.      
PS C:\Users\yousu\OneDrive\Desktop\NFT's\tweartgenerator\ArtGeneratorUpdated-main> node index.js 
(node:19936) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Created edition: 1, with DNA: 9f4a94d3c0c377b98c8afbc8bd47a782a34e9d02
Created edition: 2, with DNA: 0b8b5119117b74ac8ab3414c98b02b3c8f03654a
Created edition: 3, with DNA: 4c280ccda4e8a66043adcc9cb51b59bb3d464a16

**Comment by patriciodiass** [comment]
Te fodeer
